-- PJJ Produções — analytics simples para site estático
-- Execute no SQL Editor do Supabase.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  session_id text not null,
  page_path text,
  referrer_host text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.analytics_events enable row level security;

-- Site público pode registrar eventos.
drop policy if exists "public can insert analytics" on public.analytics_events;
create policy "public can insert analytics"
on public.analytics_events
for insert
to anon
with check (true);

-- Painel simples usa a mesma chave pública para ler as métricas.
-- IMPORTANTE: isso significa que as métricas não são consideradas secretas.
drop policy if exists "public can read analytics" on public.analytics_events;
create policy "public can read analytics"
on public.analytics_events
for select
to anon
using (true);

create index if not exists analytics_events_created_at_idx
on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_idx
on public.analytics_events (event_name);
